//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutatabiDownhill.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FutatabiDownhill.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [HEADER]
        ///VERSION=3
        ///CAMERA_COUNT=47
        ///SET_NAME=TV1
        ///
        ///[CAMERA_0]
        ///NAME=CAM0
        ///POSITION=1573.81 ,93.5758 ,-655.416
        ///FORWARD=-0.690556 ,-0.230411 ,-0.685599
        ///UP=-0.163511 ,0.973093 ,-0.162337
        ///MIN_FOV=27
        ///MAX_FOV=27
        ///IN_POINT=0
        ///OUT_POINT=0.00461007
        ///SHADOW_SPLIT0=180
        ///SHADOW_SPLIT1=420
        ///SHADOW_SPLIT2=780
        ///NEAR_PLANE=1
        ///FAR_PLANE=5000
        ///MIN_EXPOSURE=0.35
        ///MAX_EXPOSURE=0.55
        ///DOF_FACTOR=10
        ///DOF_RANGE=10000
        ///DOF_FOCUS=0
        ///DOF_MANUAL=0
        ///SPLINE=
        ///SPLINE_ROTATION=0
        ///FOV_GAMMA=1
        ///SPLINE_ANIMATION_LENGTH=15
        ///IS_FIXED=0
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cameras {
            get {
                return ResourceManager.GetString("cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] downhill_ui_track {
            get {
                object obj = ResourceManager.GetObject("downhill_ui_track", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ext_config {
            get {
                return ResourceManager.GetString("ext_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fast_lane {
            get {
                object obj = ResourceManager.GetObject("fast_lane", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] futatabi_downhill_kn5 {
            get {
                object obj = ResourceManager.GetObject("futatabi_downhill_kn5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] map_downhill {
            get {
                object obj = ResourceManager.GetObject("map_downhill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PARAMETERS]
        ///WIDTH=1599
        ///HEIGHT=2067
        ///X_OFFSET=40.6687507629395
        ///Z_OFFSET=2732.42016601563
        ///MARGIN=10
        ///SCALE_FACTOR=1
        ///DRAWING_SIZE=10
        ///
        ///.
        /// </summary>
        internal static string map_downhill_ini {
            get {
                return ResourceManager.GetString("map_downhill_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] map_uphill {
            get {
                object obj = ResourceManager.GetObject("map_uphill", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PARAMETERS]
        ///WIDTH=1555
        ///HEIGHT=2010
        ///X_OFFSET=39.1077079772949
        ///Z_OFFSET=2704.0732421875
        ///MARGIN=10.1015224456787
        ///SCALE_FACTOR=0.99900096654892
        ///DRAWING_SIZE=10
        ///
        ///.
        /// </summary>
        internal static string map_uphill_ini {
            get {
                return ResourceManager.GetString("map_uphill_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] outline {
            get {
                object obj = ResourceManager.GetObject("outline", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] outline_cropped {
            get {
                object obj = ResourceManager.GetObject("outline_cropped", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] preview {
            get {
                object obj = ResourceManager.GetObject("preview", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] uphill_ui_track {
            get {
                object obj = ResourceManager.GetObject("uphill_ui_track", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
